2024-11-02 22:30:47,762 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-02 22:31:08,647 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-04 18:28:10,528 - app.utils - INFO - Imagen del contenedor guardada en: /home/ec2-user/aws_edfcatalogoqr/app/static/container_pics/2ddd5a2ff6dd53f1.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/utils.py:108]
2024-11-04 18:46:43,763 - app - INFO - Aplicaci贸n Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:57]
2024-11-04 18:46:43,953 - app.models - INFO - Desconexi贸n exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:23]
2024-11-04 18:46:43,994 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:29]
2024-11-06 16:20:32,410 - app - INFO - Aplicaci贸n Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:57]
2024-11-06 16:20:32,566 - app.models - INFO - Desconexi贸n exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:23]
2024-11-06 16:20:32,605 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:29]
