2024-11-02 12:37:42,807 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-02 12:37:59,547 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-02 12:38:16,331 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-02 12:39:58,960 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:57]
2024-11-02 12:39:59,056 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:23]
2024-11-02 12:39:59,098 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:29]
2024-11-02 12:40:35,423 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-02 12:42:25,219 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:57]
2024-11-02 12:42:25,313 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:23]
2024-11-02 12:42:25,356 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:29]
2024-11-02 12:42:35,085 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:57]
2024-11-02 12:42:35,181 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:23]
2024-11-02 12:42:35,220 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:29]
2024-11-02 12:42:47,539 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-02 12:43:04,167 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-02 12:43:53,447 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
