2024-09-21 11:03:02,501 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:150]
2024-09-21 11:03:02,502 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: f04e2644614b7ed0.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:157]
2024-09-21 11:17:54,049 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:150]
2024-09-21 11:17:54,049 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: f04e2644614b7ed0.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:157]
2024-09-21 16:49:04,220 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:150]
2024-09-21 16:49:04,220 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: f04e2644614b7ed0.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:157]
2024-09-21 17:02:27,038 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:150]
2024-09-21 17:02:27,038 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: f04e2644614b7ed0.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:157]
2024-09-21 17:05:27,979 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:150]
2024-09-21 17:05:27,980 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: f04e2644614b7ed0.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:157]
2024-09-21 18:24:48,482 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-21 18:24:48,665 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-21 18:24:48,707 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-21 18:24:48,768 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-21 18:24:48,814 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-21 18:24:48,908 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-21 18:24:49,006 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-21 18:24:49,013 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-21 18:24:49,111 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-21 18:35:03,799 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-21 18:35:04,007 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-21 18:35:04,069 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-21 18:35:04,099 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-21 18:35:04,182 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-21 18:35:04,331 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-21 18:35:04,411 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-21 18:35:04,417 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-21 18:35:04,489 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-21 19:02:37,427 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-21 19:02:37,635 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-21 19:02:37,679 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-21 19:02:37,741 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-21 19:02:37,856 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-21 19:02:37,916 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-21 19:02:38,017 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-21 19:02:38,076 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-21 19:02:38,146 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-21 19:10:27,907 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-21 19:10:28,124 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-21 19:10:28,192 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-21 19:10:28,197 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-21 19:10:28,206 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-21 19:10:28,431 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-21 19:10:28,437 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-21 19:10:28,526 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-21 19:10:28,537 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-22 13:01:06,571 - app - ERROR - Exception on /reset_password [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 171, in reset_request
    send_reset_email(user)
  File "/home/ec2-user/aws_edfcatalogoqr/app/utils.py", line 155, in send_reset_email
    token = user.get_reset_token()
  File "/home/ec2-user/aws_edfcatalogoqr/app/models.py", line 66, in get_reset_token
    return s.dumps({'user_id': str(self.id)})  # Eliminar .decode('utf-8')8')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/itsdangerous/serializer.py", line 317, in dumps
    rv = self.make_signer(salt).sign(payload)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/itsdangerous/timed.py", line 51, in sign
    return value + sep + self.get_signature(value)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/itsdangerous/signer.py", line 218, in get_signature
    key = self.derive_key()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/itsdangerous/signer.py", line 204, in derive_key
    bytes, self.digest_method(self.salt + b"signer" + secret_key).digest()
TypeError: unsupported operand type(s) for +: 'int' and 'bytes'
2024-09-22 17:40:47,688 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:150]
2024-09-22 17:40:47,688 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: f04e2644614b7ed0.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:157]
2024-09-22 17:40:55,086 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:150]
2024-09-22 17:40:55,086 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: f04e2644614b7ed0.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:157]
2024-09-22 18:11:26,829 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-22 18:11:26,838 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-22 18:11:27,011 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-22 18:11:27,083 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-22 18:11:27,099 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-22 18:11:27,189 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-22 18:11:27,195 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-22 18:11:27,195 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
