2024-09-10 13:02:06,360 - app.routes - INFO - El nombre del contenedor ha cambiado, verificando si ya está en uso. [in /home/ec2-user/edf_catalogacion_qr/app/routes.py:348]
2024-09-10 13:02:06,373 - app.routes - INFO - Imágenes recibidas: [<FileStorage: 'IMG_6066.jpeg' ('image/jpeg')>] [in /home/ec2-user/edf_catalogacion_qr/app/routes.py:355]
2024-09-10 13:02:06,451 - app.utils - INFO - Imagen del contenedor guardada en: /home/ec2-user/edf_catalogacion_qr/app/static/container_pics/eec2a55f9652ab6f.jpeg [in /home/ec2-user/edf_catalogacion_qr/app/utils.py:97]
2024-09-10 13:02:06,488 - app.routes - INFO - Contenedor 66c38359a27a53bf0572a664 guardado exitosamente. [in /home/ec2-user/edf_catalogacion_qr/app/routes.py:369]
2024-09-10 13:04:33,740 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/edf_catalogacion_qr/app/routes.py:156]
2024-09-10 13:04:33,741 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: 87371de9a20d1e8d.jpeg [in /home/ec2-user/edf_catalogacion_qr/app/routes.py:166]
2024-09-10 13:20:16,805 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/edf_catalogacion_qr/app/routes.py:156]
2024-09-10 13:20:16,806 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: 87371de9a20d1e8d.jpeg [in /home/ec2-user/edf_catalogacion_qr/app/routes.py:166]
2024-09-10 13:30:01,709 - app.routes - INFO - Creación de contenedor iniciada. [in /home/ec2-user/edf_catalogacion_qr/app/routes.py:235]
2024-09-10 13:30:01,767 - app.utils - INFO - Imagen del contenedor guardada en: /home/ec2-user/edf_catalogacion_qr/app/static/container_pics/861020f5a6279a3c.jpeg [in /home/ec2-user/edf_catalogacion_qr/app/utils.py:97]
2024-09-10 13:30:01,808 - app.routes - INFO - Contenedor creado con ID: 66e049d95e1cfef1fa2dca31 [in /home/ec2-user/edf_catalogacion_qr/app/routes.py:276]
2024-09-10 14:59:12,757 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/edf_catalogacion_qr/app/__init__.py:70]
2024-09-10 14:59:12,838 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:26]
2024-09-10 14:59:12,874 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:33]
2024-09-10 15:12:14,066 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/edf_catalogacion_qr/app/__init__.py:70]
2024-09-10 15:12:14,146 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:26]
2024-09-10 15:12:14,185 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:33]
2024-09-10 15:18:32,039 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/edf_catalogacion_qr/app/__init__.py:70]
2024-09-10 15:18:32,121 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:26]
2024-09-10 15:18:32,159 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:33]
2024-09-10 15:34:30,493 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/edf_catalogacion_qr/app/routes.py:156]
2024-09-10 15:34:30,493 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: 87371de9a20d1e8d.jpeg [in /home/ec2-user/edf_catalogacion_qr/app/routes.py:166]
2024-09-10 16:32:29,669 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/edf_catalogacion_qr/app/__init__.py:70]
2024-09-10 16:32:29,749 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:26]
2024-09-10 16:32:29,785 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:33]
2024-09-10 16:41:37,287 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/edf_catalogacion_qr/app/__init__.py:70]
2024-09-10 16:41:37,366 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:26]
2024-09-10 16:41:37,402 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:33]
2024-09-10 17:18:48,483 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/edf_catalogacion_qr/app/routes.py:156]
2024-09-10 17:18:48,483 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: 87371de9a20d1e8d.jpeg [in /home/ec2-user/edf_catalogacion_qr/app/routes.py:166]
2024-09-10 17:31:55,116 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/edf_catalogacion_qr/app/__init__.py:70]
2024-09-10 17:31:55,196 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:26]
2024-09-10 17:31:55,233 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:33]
2024-09-10 17:32:55,023 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/edf_catalogacion_qr/app/__init__.py:70]
2024-09-10 17:32:55,104 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:26]
2024-09-10 17:32:55,141 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:33]
2024-09-10 17:33:52,469 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/edf_catalogacion_qr/app/__init__.py:70]
2024-09-10 17:33:52,552 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:26]
2024-09-10 17:33:52,587 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:33]
2024-09-10 17:35:19,547 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/edf_catalogacion_qr/app/__init__.py:70]
2024-09-10 17:35:19,628 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:26]
2024-09-10 17:35:19,667 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:33]
2024-09-10 17:36:54,996 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/edf_catalogacion_qr/app/__init__.py:70]
2024-09-10 17:36:55,076 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:26]
2024-09-10 17:36:55,112 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:33]
2024-09-10 17:41:29,389 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/edf_catalogacion_qr/app/__init__.py:70]
2024-09-10 17:41:29,469 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:26]
2024-09-10 17:41:29,505 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/edf_catalogacion_qr/app/models.py:33]
2024-09-10 17:41:34,304 - app - ERROR - Exception on /about [GET] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/edf_catalogacion_qr/app/routes.py", line 60, in about
    return render_template('about.html', title='Acerca de')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ec2-user/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ec2-user/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ec2-user/edf_catalogacion_qr/app/templates/about.html", line 22, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
