2024-11-02 12:50:04,114 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-02 17:51:39,388 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-02 18:01:39,884 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-02 19:26:22,447 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-02 19:30:19,268 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:57]
2024-11-02 19:30:19,367 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:23]
2024-11-02 19:30:19,408 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:29]
2024-11-02 22:27:40,734 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:57]
2024-11-02 22:27:40,827 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:23]
2024-11-02 22:27:40,871 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:29]
2024-11-02 22:28:43,064 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-02 22:29:13,230 - app.utils - INFO - Correo de restablecimiento de contraseña enviado a edfrutos@gmail.com [in /home/ec2-user/aws_edfcatalogoqr/app/utils.py:164]
2024-11-02 22:29:36,041 - app.models - INFO - Token válido para el usuario ID: 66a21c1c106d5c0ec264b152 [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:71]
2024-11-02 22:29:44,513 - app.models - INFO - Token válido para el usuario ID: 66a21c1c106d5c0ec264b152 [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:71]
2024-11-02 22:29:44,908 - app.models - INFO - Token válido para el usuario ID: 66a21c1c106d5c0ec264b152 [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:71]
2024-11-02 22:29:45,308 - app.models - INFO - Token válido para el usuario ID: 66a21c1c106d5c0ec264b152 [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:71]
2024-11-02 22:30:28,933 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
2024-11-02 22:30:38,707 - app - ERROR - Exception on /login [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 74, in login
    if user and bcrypt.check_password_hash(user.password, form.password.data):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask_bcrypt.py", line 225, in check_password_hash
    return hmac.compare_digest(bcrypt.hashpw(password, pw_hash), pw_hash)
ValueError: Invalid salt
